// Converts the prototype's Lucide icon set (project/lz-icon.js) into SVG path strings
// for LzIconPaths.kt. Run: node android/tools/gen-icons.mjs > android/app/src/main/java/com/lezerv/app/ui/icons/LzIconPaths.kt
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const src = readFileSync(fileURLToPath(new URL('../../project/lz-icon.js', import.meta.url)), 'utf8');
const table = src.slice(src.indexOf('const P={') + 8, src.indexOf('};\nclass')) + '}';
const P = Function('return ' + table)();

const attrs = s => Object.fromEntries([...s.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
const n = v => +(v ?? 0);

function toPath(tag, a) {
  switch (tag) {
    case 'path': return a.d;
    case 'circle': { const cx = n(a.cx), cy = n(a.cy), r = n(a.r);
      return `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0z`; }
    case 'line': return `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`;
    case 'polygon': { const p = a.points.trim().split(/[\s,]+/).map(Number), out = [];
      for (let i = 0; i < p.length; i += 2) out.push((i ? 'L' : 'M') + p[i] + ' ' + p[i + 1]);
      return out.join('') + 'z'; }
    case 'rect': { const x = n(a.x), y = n(a.y), w = n(a.width), h = n(a.height), r = n(a.rx ?? a.ry);
      if (!r) return `M${x} ${y}h${w}v${h}h${-w}z`;
      return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}z`; }
  }
  throw new Error('unsupported ' + tag);
}

let out = `// GENERATED by android/tools/gen-icons.mjs from project/lz-icon.js (Lucide, ISC licence). Do not edit.
package com.lezerv.app.ui.icons

internal val LzIconPaths: Map<String, List<String>> = mapOf(
`;
for (const [name, svg] of Object.entries(P)) {
  const paths = [...svg.matchAll(/<(\w+)\s([^>]*?)\/?>/g)].map(m => toPath(m[1], attrs(m[2])));
  out += `    "${name}" to listOf(${paths.map(p => JSON.stringify(p)).join(', ')}),\n`;
}
out += ')\n';
process.stdout.write(out);
